language: java

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9c48a5b54587_key -iv $encrypted_9c48a5b54587_iv
    -in gradle-local.properties.enc -out gradle-local.properties -d
  - docker pull alvrme/alpine-android:android-29
  - docker run -it -d --name test alvrme/alpine-android:android-29 bash
  - docker cp . test:/home/android

install: true

before_script:
  - docker exec test echo "org.gradle.daemon=false" >> gradle.properties
  - docker exec test echo "org.gradle.parallel=true" >> gradle.properties
  - docker exec test chmod +x ./gradlew

script: docker exec test ./gradlew -Pci --console=plain :app:testDebug